# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b74ee13023a9f564816a81dc5bc48d72419be39fca2bf0d1f8388f6a8dac53efd3e0e8d03f65b442d248f53dabe5d6305d898dfb148f223cd0452ca8950c8fdf

test:
  secret_key_base: 20810205f5c2f4246c4db3111ddbb8a4f6d5d5b1438612308661323bfa8ca02dde3837ac0b777bdd184bfd692882657fd98b749d1f7b5e34dec1647d6fc01771

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
